export const IPC = {
  GET_STATUS: "mcpx:get-status",
  GET_SERVERS: "mcpx:get-servers",
  GET_DESKTOP_SETTINGS: "mcpx:get-desktop-settings",
  ADD_SERVER: "mcpx:add-server",
  UPDATE_SERVER: "mcpx:update-server",
  REMOVE_SERVER: "mcpx:remove-server",
  SET_SERVER_ENABLED: "mcpx:set-server-enabled",
  UPDATE_DESKTOP_SETTINGS: "mcpx:update-desktop-settings",
  CHECK_FOR_UPDATES: "mcpx:check-for-updates",
  SYNC_ALL: "mcpx:sync-all",
  DAEMON_START: "mcpx:daemon-start",
  DAEMON_STOP: "mcpx:daemon-stop",
  DAEMON_RESTART: "mcpx:daemon-restart",
  REGISTRY_LIST: "mcpx:registry-list",
  REGISTRY_GET: "mcpx:registry-get",
  REGISTRY_PREPARE_ADD: "mcpx:registry-prepare-add",
  REGISTRY_CONFIRM_ADD: "mcpx:registry-confirm-add",
  OPEN_DASHBOARD: "mcpx:open-dashboard",
  EXECUTE_CLI_COMMAND: "mcpx:execute-cli-command"
} as const;
